/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                background: "#0A0A0B",
                surface: "#0A0A0B",
                "surface-dim": "#0A0A0B",
                "surface-bright": "#373b2c",
                "surface-tint": "#a8d700",
                "surface-variant": "#333627",
                "surface-container": "#1d2113",
                "surface-container-low": "#191d10",
                "surface-container-high": "#282c1d",
                "surface-container-highest": "#333627",
                "surface-container-lowest": "#050506",
                "on-surface": "#e1e4cf",
                "on-surface-variant": "#c4caac",
                "on-background": "#e1e4cf",
                primary: "#ffffff",
                "on-primary": "#273500",
                "primary-container": "#c0f500",
                "primary-fixed": "#c0f500",
                "primary-fixed-dim": "#a8d700",
                "on-primary-fixed": "#161f00",
                "on-primary-fixed-variant": "#3b4d00",
                "on-primary-container": "#546d00",
                secondary: "#b3d25e",
                "on-secondary": "#273500",
                "secondary-container": "#597400",
                "secondary-fixed": "#ceef77",
                "secondary-fixed-dim": "#b3d25e",
                "on-secondary-fixed": "#161f00",
                "on-secondary-fixed-variant": "#3b4d00",
                "on-secondary-container": "#d8f97f",
                tertiary: "#ffffff",
                "on-tertiary": "#1f333f",
                "tertiary-container": "#d0e5f5",
                "tertiary-fixed": "#d0e5f5",
                "tertiary-fixed-dim": "#b5c9d9",
                "on-tertiary-fixed": "#081e29",
                "on-tertiary-fixed-variant": "#364956",
                "on-tertiary-container": "#536774",
                error: "#ffb4ab",
                "on-error": "#690005",
                "error-container": "#93000a",
                "on-error-container": "#ffdad6",
                outline: "#8e9479",
                "outline-variant": "#434933",
                "inverse-surface": "#e1e4cf",
                "inverse-on-surface": "#2e3223",
                "inverse-primary": "#4f6600",
                lime: "#c8ff00",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                gutter: "32px",
                "stack-sm": "8px",
                "stack-md": "24px",
                "stack-lg": "64px",
                "section-padding": "160px",
                "container-max": "1440px",
            },
            maxWidth: {
                "container-max": "1440px",
            },
            fontFamily: {
                sora: ["Sora", "sans-serif"],
                inter: ["Inter", "sans-serif"],
                mono: ["JetBrains Mono", "monospace"],
            },
            fontSize: {
                "display-lg": ["84px", { lineHeight: "90%", letterSpacing: "-0.04em", fontWeight: "800" }],
                "display-lg-mobile": ["48px", { lineHeight: "100%", letterSpacing: "-0.04em", fontWeight: "800" }],
                "headline-lg": ["48px", { lineHeight: "110%", letterSpacing: "-0.03em", fontWeight: "700" }],
                "headline-lg-mobile": ["32px", { lineHeight: "110%", letterSpacing: "-0.03em", fontWeight: "700" }],
                "headline-md": ["32px", { lineHeight: "120%", letterSpacing: "-0.02em", fontWeight: "600" }],
                "body-lg": ["20px", { lineHeight: "160%", letterSpacing: "-0.01em", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "160%", letterSpacing: "0em", fontWeight: "400" }],
                "label-mono": ["14px", { lineHeight: "100%", letterSpacing: "0.05em", fontWeight: "500" }],
            },
            keyframes: {
                "marquee-left": {
                    "0%": { transform: "translateX(0)" },
                    "100%": { transform: "translateX(-50%)" },
                },
                "marquee-right": {
                    "0%": { transform: "translateX(-50%)" },
                    "100%": { transform: "translateX(0)" },
                },
            },
            animation: {
                "marquee-left": "marquee-left 30s linear infinite",
                "marquee-right": "marquee-right 30s linear infinite",
            },
        },
    },
    plugins: [],
};
